[misc] check GPU in nvman

diff --git a/.local/bin/nvman b/.local/bin/nvman
--- a/.local/bin/nvman
+++ b/.local/bin/nvman
@@ -100,6 +100,10 @@ list() {
     set -euo pipefail
 }
 
+set +o pipefail
+lspci | grep -iq nvidia || die "GPU not found"
+set -o pipefail
+
 if [[ $# -eq 0 ]]; then
     help
 fi
