[zsh] use bs.sh in drun

diff --git a/.dotfiles/bin/drun b/.dotfiles/bin/drun
--- a/.dotfiles/bin/drun
+++ b/.dotfiles/bin/drun
@@ -4,9 +4,17 @@
 
 set -euo pipefail
 
-env() {
-    name=$1
+if [[ -f "$HOME/.dotfiles/files/bs.sh" ]]; then
+    # shellcheck source=/dev/null
+    source "$HOME/.dotfiles/files/bs.sh"
+else
+    eval "$(curl -fsSL https://raw.githubusercontent.com/nevillelyh/dotfiles/main/.dotfiles/files/bs.sh)"
+fi
 
+env() {
+    local name=$1
+
+    local default
     if [[ $# -eq 2 ]]; then
         default=$2
     else
@@ -25,39 +33,35 @@ env() {
             ZK_PORT) default=2181 ;;
         esac
     fi
-    value=${!name:-$default}
-    color='\033[1;33m' # yellow
-    reset='\033[0m' #reset
-    echo >&2 -e "$color$name=$value$reset"
+    local value=${!name:-$default}
+    echo >&2 -e "$(bs_warn "$name=$value")"
     echo "$value"
 }
 
 docker_run() {
-    color='\033[1;32m' # green
-    reset='\033[0m' #reset
-    echo >&2 -e "${color}docker run $*${reset}"
+    echo >&2 -e "$(bs_success "docker run $*")"
     docker run --label dotfiles.bin.drun=true "$@"
 }
 
 docker_srv() {
-    name=$1
+    local name=$1
     shift
     docker_run --name "$name" -d --rm "$@"
     docker logs -f "$name"
 }
 
 docker_cli() {
-    name=$1
+    local name=$1
     shift
     # TTY for CLIs, e.g. psql
-    docker_run --name "$name-$(date "+%Y%m%d%H%M%S")" -it --rm --network host "$@"
+    docker_run --name "$name-$(bs_timestamp)" -it --rm --network host "$@"
 }
 
 docker_cmd() {
-    name=$1
+    local name=$1
     shift
     # no TTY for commands with stdin/stdout, e.g. kcat
-    docker_run --name "$name-$(date "+%Y%m%d%H%M%S")" -i --rm --network host "$@"
+    docker_run --name "$name-$(bs_timestamp)" -i --rm --network host "$@"
 }
 
 run_killall() {
@@ -79,13 +83,15 @@ run_cockroach() {
 }
 
 run_cockroach-sql() {
+    local url
     url="postgresql://$(env DB_USER):$(env DB_PASS)@localhost:$(env COCKROACH_PORT)/$(env DB)?sslmode=require"
     docker_cli cockroach-cli \
         cockroachdb/cockroach:latest sql --url "$url" "$@"
 }
 
 run_kafka() {
-    host=127.0.0.1 # workaround for IPv6 issue
+    local host=127.0.0.1 # workaround for IPv6 issue
+    local port
     port=$(env KAFKA_PORT)
     docker_srv kafka \
         --env KAFKA_BROKER_ID=1 \
@@ -105,7 +111,7 @@ run_kafka() {
 }
 
 run_kcat() {
-    host=127.0.0.1 # workaround for IPv6 issue
+    local host=127.0.0.1 # workaround for IPv6 issue
     docker_cmd kcat \
         nevillelyh/kcat:latest -b "$host:$(env KAFKA_PORT)" "$@"
 }
@@ -191,26 +197,26 @@ run_zookeeper() {
 get_commands() {
     # Bash 3 on Mac missing readarray
     # shellcheck disable=SC2207
-    commands=($(grep -o '^run_.\+()' "$(readlink -f "$0")" | sed 's/^run_\(.*\)()$/\1/'))
+    cmds=($(grep -o '^run_.\+()' "$(readlink -f "$0")" | sed 's/^run_\(.*\)()$/\1/'))
 }
 
 if [[ $# -eq 0 ]]; then
     echo "Usage: $(basename "$0") <COMMAND> [ARG]..."
     echo "    Commands"
     get_commands
-    for c in "${commands[@]}"; do
+    for c in "${cmds[@]}"; do
         echo "        $c"
     done
     exit 1
 fi
 
-command=$(basename "$1")
+cmd=$(basename "$1")
 shift
 
 get_commands
-if [[ " ${commands[*]} " =~ (^|[[:space:]])"$command"($|[[:space:]]) ]]; then
-    "run_$command" "$@"
+if [[ "$(bs_array_contains "$cmd" "${cmds[@]}")" == 0 ]]; then
+    "run_$cmd" "$@"
 else
-    echo "Command not found: $command"
+    echo "Command not found: $cmd"
     exit 1
 fi
